Feature/setup
Benawi/Hello-rails-react pull request #1
Opened 2023-10-10 18:19 UTC by Benawi

## [Implemented Features](https://github.com/microverseinc/curriculum-rails/blob/main/connect-frontend-frameworks/rails_react_webpack.md)
### General requirements
- [x]  Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- [x] Make sure that you used the correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- [x] Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
### Ruby requirements
- [x]  Follow our list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).
 ### JavaScript requirements
- [x] Follow our list of best practices for JavaScript.
### Project requirements

 - Create a new Rails app called 'hello-rails-react'.
      - Use the command `rails new -j webpack my_new_rails_app` as described in the previous lesson's tutorial.
 - Verify that the `jsbundling-rails` gem is added to your Gemfile.
 - Initialize your project with Git.
 - Install needed node dependencies as described in the previous lesson's tutorial.
 - Create a `babel.config.js` in the root folder of your project as described in the previous lesson's tutorial.
 - Update `webpack.config.js` to include the babel loader as described in the previous lesson's tutorial.
 - Make sure that your project has a Postgres database set up. 
 - Create a table for storing your messages and create 5 different greetings. 
 - Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
 - Create a static view that will be the root of your app.

2023-10-10 21:35 UTC, Omar-Muhamad reviewed
# Invalid ❌

Hi @Benawi,

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [ ] Linters GitHub actions are not working. Please configure it.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2023-10-10 22:40 UTC, Felix45 requested changes
Hi @Benawi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://camo.githubusercontent.com/59fa9d95c18dbd5a8e47490a9e4b48393f569685410f3c78d4d83a9764fa1392/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e676966" width="350px" />

## Highlights :heavy_check_mark: 
- [x] `React` and `Rails` parts of the application have been setup correctly :white_check_mark: 
- [x] Repositopry has a professional readme file :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark:  
- [x] Pull request has a descriptive summary :white_check_mark:  


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-10 22:40 UTC, Felix45 commented on db/seeds.rb
- [ Required ] I think it would be nice if you create a `migration` that can be run to create the `message` table. Currently, there is no migration file that can be used to create this table in the database. Since the migration file is missing it's not possible for me to test if the greetings `api` works as expected. Kindly fix this and ensure that the `greetings` can be stored in the database and retrieved by sending a `GET` request to the `/api/greetings/random` endpoint.

## Error when accessing the API
> I think this error occurs because of the missing migration file

![Screenshot from 2023-10-11 01-25-45](https://github.com/Benawi/Hello-rails-react/assets/16392046/454e9a04-7173-4796-a154-4301532bfb7c)

2023-10-10 22:40 UTC, Felix45 commented on app/javascript/application.js
> +}
- [ Required ] I think it would be nice if you ensure that the `React` and `Rails` parts of the App work together. To do this please ensure that you can start the application with `./bin/dev` command, currently, this application fails to start when this command is used to run the `App`.

**NB**
The `React` part of the application should display a greeting message from `Rails` endpoint `http://127.0.0.1:3000/api/greetings/random`

2023-10-11 00:51 UTC, Benawi commented
### Changes
- [x] Create a migration
- [x] The greetings API works as expected.
- [x] The React and Rails parts of the App work together

2023-10-11 04:15 UTC, braincee approved these changes
Hi @Benawi  , I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![youre-approved-shirley-auto-group](https://user-images.githubusercontent.com/78104544/226852457-95ef4c1d-5d51-4f76-abd8-1fdc06b89e77.gif)

OPTIONAL CHANGES
---

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-10-11 06:32 UTC, merged